# Makefile for Monopoly Game

# Compiler and flags
CXX = g++
CXXFLAGS = -Wall -Wextra -std=c++11 -I include -lsfml-graphics -lsfml-window -lsfml-system

# Source files
SRCS = main.cpp \
       Player.cpp \
       Slot.cpp \
       Street.cpp \
       Train.cpp \
       Utility.cpp \
       Surprise.cpp \
       Tax.cpp \
       Jail.cpp \
       FreeParking.cpp \
       GoToJail.cpp \
       Board.cpp

# Header files
HEADERS = Player.hpp \
          Slot.hpp \
          Street.hpp \
          Train.hpp \
          Utility.hpp \
          Surprise.hpp \
          Tax.hpp \
          Jail.hpp \
          FreeParking.hpp \
          GoToJail.hpp \
          Board.hpp

# Output executable
TARGET = monopoly

# Rule to build the executable
all: $(TARGET)

$(TARGET): $(SRCS) $(HEADERS)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(SRCS)

# Rule for cleaning up
clean:
	rm -f $(TARGET) *.o


